# Generated by Django 4.1.1 on 2022-10-03 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('date_consumed', models.DateTimeField(auto_now_add=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('dietary_fiber', models.FloatField(blank=True, null=True)),
                ('vitamin_A', models.FloatField(blank=True, null=True)),
                ('vitamin_D', models.FloatField(blank=True, null=True)),
                ('vitamin_E', models.FloatField(blank=True, null=True)),
                ('vitamin_K', models.FloatField(blank=True, null=True)),
                ('thiamin', models.FloatField(blank=True, null=True)),
                ('riboflavin', models.FloatField(blank=True, null=True)),
                ('niacin', models.FloatField(blank=True, null=True)),
                ('vitamin_B6', models.FloatField(blank=True, null=True)),
                ('vitamin_B12', models.FloatField(blank=True, null=True)),
                ('folate', models.FloatField(blank=True, null=True)),
                ('vitamin_C', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
                ('selenium', models.FloatField(blank=True, null=True)),
                ('iodine', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('magnesium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('flouride', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('chloride', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
