# Generated by Django 4.1.1 on 2022-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_consumed',
            field=models.DateTimeField(),
        ),
    ]
